<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * External services definition for tool_management_console.
 *
 * @package    tool_management_console
 * @copyright  2026 Hector Teran
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$functions = [
    'tool_management_console_get_users_kpis' => [
        'classname'     => 'tool_management_console\external\users',
        'methodname'    => 'get_users_kpis',
        'description'   => 'Get global user KPIs (totals, active, suspended, avg progress)',
        'type'          => 'read',
        'capabilities'  => 'moodle/user:viewalldetails',
        'ajax'          => true,
    ],
    'tool_management_console_get_dashboard' => [
        'classname'     => 'tool_management_console\external\dashboard',
        'methodname'    => 'get_dashboard',
        'description'   => 'Get dashboard overview counters',
        'type'          => 'read',
        'capabilities'  => 'moodle/site:config',
        'ajax'          => true,
    ],
    'tool_management_console_get_courses' => [
        'classname'     => 'tool_management_console\external\courses',
        'methodname'    => 'get_courses',
        'description'   => 'Get paginated courses with filtering and stats',
        'type'          => 'read',
        'capabilities'  => 'moodle/course:view',
        'ajax'          => true,
    ],
    'tool_management_console_course_action' => [
        'classname'     => 'tool_management_console\external\courses',
        'methodname'    => 'course_action',
        'description'   => 'Execute individual or bulk actions on courses',
        'type'          => 'write',
        'capabilities'  => 'moodle/course:update',
        'ajax'          => true,
    ],
    'tool_management_console_get_categories' => [
        'classname'     => 'tool_management_console\external\categories',
        'methodname'    => 'get_categories',
        'description'   => 'Get paginated categories with course count and visibility',
        'type'          => 'read',
        'capabilities'  => 'moodle/category:viewhiddencategories',
        'ajax'          => true,
    ],
    'tool_management_console_get_categories_flat' => [
        'classname'     => 'tool_management_console\external\categories',
        'methodname'    => 'get_categories_flat',
        'description'   => 'Get flat list of all categories for selects/dropdowns',
        'type'          => 'read',
        'capabilities'  => 'moodle/category:viewhiddencategories',
        'ajax'          => true,
    ],
    'tool_management_console_category_action' => [
        'classname'     => 'tool_management_console\external\categories',
        'methodname'    => 'category_action',
        'description'   => 'Execute create, update, delete or visibility action on categories',
        'type'          => 'write',
        'capabilities'  => 'moodle/category:manage',
        'ajax'          => true,
    ],
    'tool_management_console_get_users' => [
        'classname'     => 'tool_management_console\external\users',
        'methodname'    => 'get_users',
        'description'   => 'Get paginated users with enrollments, completions, and progress',
        'type'          => 'read',
        'capabilities'  => 'moodle/user:viewalldetails',
        'ajax'          => true,
    ],
    'tool_management_console_user_action' => [
        'classname'     => 'tool_management_console\external\users',
        'methodname'    => 'user_action',
        'description'   => 'Execute suspend, activate, delete, message or temporary password actions on users',
        'type'          => 'write',
        'capabilities'  => 'moodle/user:update',
        'ajax'          => true,
    ],
    'tool_management_console_get_cohorts_kpis' => [
        'classname'     => 'tool_management_console\external\cohorts',
        'methodname'    => 'get_cohorts_kpis',
        'description'   => 'Get global cohort KPIs (totals, members, synced courses)',
        'type'          => 'read',
        'capabilities'  => 'moodle/cohort:view',
        'ajax'          => true,
    ],
    'tool_management_console_get_cohorts' => [
        'classname'     => 'tool_management_console\external\cohorts',
        'methodname'    => 'get_cohorts',
        'description'   => 'Get paginated list of cohorts and member counts',
        'type'          => 'read',
        'capabilities'  => 'moodle/cohort:view',
        'ajax'          => true,
    ],
    'tool_management_console_cohort_action' => [
        'classname'     => 'tool_management_console\external\cohorts',
        'methodname'    => 'cohort_action',
        'description'   => 'Execute create, edit or delete actions on cohorts',
        'type'          => 'write',
        'capabilities'  => 'moodle/cohort:manage',
        'ajax'          => true,
    ],
    'tool_management_console_get_course_detail' => [
        'classname'     => 'tool_management_console\external\courses',
        'methodname'    => 'get_course_detail',
        'description'   => 'Get course details including enrolled users and linked cohorts',
        'type'          => 'read',
        'capabilities'  => 'moodle/course:view',
        'ajax'          => true,
    ],
    'tool_management_console_course_cohort_action' => [
        'classname'     => 'tool_management_console\external\courses',
        'methodname'    => 'course_cohort_action',
        'description'   => 'Add or remove cohorts from a course',
        'type'          => 'write',
        'capabilities'  => 'moodle/course:enrolreview',
        'ajax'          => true,
    ],
    'tool_management_console_get_user_detail' => [
        'classname'     => 'tool_management_console\external\users',
        'methodname'    => 'get_user_detail',
        'description'   => 'Get user details including enrolled courses and linked cohorts',
        'type'          => 'read',
        'capabilities'  => 'moodle/user:viewalldetails',
        'ajax'          => true,
    ],
    'tool_management_console_user_cohort_action' => [
        'classname'     => 'tool_management_console\external\users',
        'methodname'    => 'user_cohort_action',
        'description'   => 'Add or remove cohorts from a user',
        'type'          => 'write',
        'capabilities'  => 'moodle/cohort:manage',
        'ajax'          => true,
    ],
    'tool_management_console_get_cohort_detail' => [
        'classname'     => 'tool_management_console\external\cohorts',
        'methodname'    => 'get_cohort_detail',
        'description'   => 'Get cohort details including members and linked courses',
        'type'          => 'read',
        'capabilities'  => 'moodle/cohort:view',
        'ajax'          => true,
    ],
    'tool_management_console_get_category_detail' => [
        'classname'     => 'tool_management_console\external\categories',
        'methodname'    => 'get_category_detail',
        'description'   => 'Get category details including subcategories and courses',
        'type'          => 'read',
        'capabilities'  => 'moodle/category:viewhiddencategories',
        'ajax'          => true,
    ],
    'tool_management_console_get_permissions' => [
        'classname'     => 'tool_management_console\external\permissions',
        'methodname'    => 'get_permissions',
        'description'   => 'Get current user adminer capabilities',
        'type'          => 'read',
        'ajax'          => true,
    ],
    'tool_management_console_add_user' => [
        'classname'     => 'tool_management_console\external\users',
        'methodname'    => 'add_user',
        'description'   => 'Add a new user',
        'type'          => 'write',
        'capabilities'  => 'moodle/user:create',
        'ajax'          => true,
    ],
    'tool_management_console_upload_users_csv' => [
        'classname'     => 'tool_management_console\external\users',
        'methodname'    => 'upload_users_csv',
        'description'   => 'Upload users via CSV',
        'type'          => 'write',
        'capabilities'  => 'moodle/user:create',
        'ajax'          => true,
    ],
    'tool_management_console_course_user_action' => [
        'classname'     => 'tool_management_console\external\courses',
        'methodname'    => 'course_user_action',
        'description'   => 'Enroll or unenroll users in a course',
        'type'          => 'write',
        'capabilities'  => 'enrol/manual:enrol',
        'ajax'          => true,
    ],
    'tool_management_console_upload_courses_csv' => [
        'classname'     => 'tool_management_console\external\courses',
        'methodname'    => 'upload_courses_csv',
        'description'   => 'Upload courses via CSV',
        'type'          => 'write',
        'capabilities'  => 'moodle/course:create',
        'ajax'          => true,
    ],
    'tool_management_console_user_course_action' => [
        'classname'     => 'tool_management_console\external\users',
        'methodname'    => 'user_course_action',
        'description'   => 'Enroll or unenroll a user in multiple courses',
        'type'          => 'write',
        'capabilities'  => 'enrol/manual:enrol',
        'ajax'          => true,
    ],
    'tool_management_console_get_course_user_detail' => [
        'classname'     => 'tool_management_console\external\courses',
        'methodname'    => 'get_course_user_detail',
        'description'   => 'Get user detail inside a course',
        'type'          => 'read',
        'capabilities'  => 'moodle/course:view',
        'ajax'          => true,
    ],
    'tool_management_console_get_autologin_url' => [
        'classname'     => 'tool_management_console\external\autologin',
        'methodname'    => 'get_autologin_url',
        'description'   => 'Get autologin url',
        'type'          => 'read',
        'ajax'          => true,
    ],
    'tool_management_console_get_scales' => [
        'classname'     => 'tool_management_console\external\competencies',
        'methodname'    => 'get_scales',
        'description'   => 'Get standard scales for competency frameworks',
        'type'          => 'read',
        'ajax'          => true,
    ],
    'tool_management_console_get_competency_kpis' => [
        'classname'     => 'tool_management_console\external\competencies',
        'methodname'    => 'get_competency_kpis',
        'description'   => 'Get competency global KPIs',
        'type'          => 'read',
        'ajax'          => true,
    ],
    'tool_management_console_get_competency_frameworks' => [
        'classname'     => 'tool_management_console\external\competencies',
        'methodname'    => 'get_competency_frameworks',
        'description'   => 'Get paginated competency frameworks',
        'type'          => 'read',
        'ajax'          => true,
    ],
    'tool_management_console_competency_framework_action' => [
        'classname'     => 'tool_management_console\external\competencies',
        'methodname'    => 'competency_framework_action',
        'description'   => 'Create, edit, delete or toggle visibility for competency frameworks',
        'type'          => 'write',
        'ajax'          => true,
    ],
    'tool_management_console_get_competency_framework_detail' => [
        'classname'     => 'tool_management_console\external\competencies',
        'methodname'    => 'get_competency_framework_detail',
        'description'   => 'Get competency framework detail and level 1 competencies',
        'type'          => 'read',
        'ajax'          => true,
    ],
    'tool_management_console_competency_action' => [
        'classname'     => 'tool_management_console\external\competencies',
        'methodname'    => 'competency_action',
        'description'   => 'Create, edit or delete competencies',
        'type'          => 'write',
        'ajax'          => true,
    ],
    'tool_management_console_get_competency_courses' => [
        'classname'     => 'tool_management_console\external\competencies',
        'methodname'    => 'get_competency_courses',
        'description'   => 'Get courses linked to a competency',
        'type'          => 'read',
        'ajax'          => true,
    ],
    'tool_management_console_competency_course_action' => [
        'classname'     => 'tool_management_console\external\competencies',
        'methodname'    => 'competency_course_action',
        'description'   => 'Link or unlink courses from a competency',
        'type'          => 'write',
        'ajax'          => true,
    ],
    'tool_management_console_get_competency_detail' => [
        'classname'     => 'tool_management_console\external\competencies',
        'methodname'    => 'get_competency_detail',
        'description'   => 'Get competency details including framework info',
        'type'          => 'read',
        'ajax'          => true,
    ],
    'tool_management_console_get_course_available_activities' => [
        'classname'     => 'tool_management_console\external\competencies',
        'methodname'    => 'get_course_available_activities',
        'description'   => 'Get course modules and check if they are linked to a competency',
        'type'          => 'read',
        'ajax'          => true,
    ],
    'tool_management_console_module_competency_action' => [
        'classname'     => 'tool_management_console\external\competencies',
        'methodname'    => 'module_competency_action',
        'description'   => 'Link, unlink or update rules for course activity competencies',
        'type'          => 'write',
        'ajax'          => true,
    ],
    'tool_management_console_get_competency_reviews' => [
        'classname'     => 'tool_management_console\external\competencies',
        'methodname'    => 'get_competency_reviews',
        'description'   => 'Get pending and in-review student competencies',
        'type'          => 'read',
        'ajax'          => true,
    ],
    'tool_management_console_competency_review_action' => [
        'classname'     => 'tool_management_console\external\competencies',
        'methodname'    => 'competency_review_action',
        'description'   => 'Evaluate, rate and complete student competency review',
        'type'          => 'write',
        'ajax'          => true,
    ],
    'tool_management_console_get_competency_users' => [
        'classname'     => 'tool_management_console\external\competencies',
        'methodname'    => 'get_competency_users',
        'description'   => 'Get enrolled and evaluated users for a competency with progress and evidences',
        'type'          => 'read',
        'ajax'          => true,
    ],
];

$services = [
    'Management Console Service' => [
        'functions' => [
            'tool_management_console_get_dashboard',
            'tool_management_console_get_courses',
            'tool_management_console_course_action',
            'tool_management_console_get_categories',
            'tool_management_console_get_categories_flat',
            'tool_management_console_category_action',
            'tool_management_console_get_users_kpis',
            'tool_management_console_get_users',
            'tool_management_console_user_action',
            'tool_management_console_add_user',
            'tool_management_console_upload_users_csv',
            'tool_management_console_get_cohorts_kpis',
            'tool_management_console_get_cohorts',
            'tool_management_console_cohort_action',
            'tool_management_console_get_course_detail',
            'tool_management_console_course_cohort_action',
            'tool_management_console_course_user_action',
            'tool_management_console_get_user_detail',
            'tool_management_console_user_cohort_action',
            'tool_management_console_user_course_action',
            'tool_management_console_get_cohort_detail',
            'tool_management_console_get_category_detail',
            'tool_management_console_get_permissions',
            'tool_management_console_get_course_user_detail',
            'tool_management_console_upload_courses_csv',
            'tool_management_console_get_autologin_url',
            'tool_management_console_get_scales',
            'tool_management_console_get_competency_kpis',
            'tool_management_console_get_competency_frameworks',
            'tool_management_console_competency_framework_action',
            'tool_management_console_get_competency_framework_detail',
            'tool_management_console_competency_action',
            'tool_management_console_get_competency_courses',
            'tool_management_console_competency_course_action',
            'tool_management_console_get_competency_detail',
            'tool_management_console_get_course_available_activities',
            'tool_management_console_module_competency_action',
            'tool_management_console_get_competency_reviews',
            'tool_management_console_competency_review_action',
            'tool_management_console_get_competency_users',
            'core_webservice_get_site_info',
        ],
        'restrictedusers' => 0,
        'enabled'         => 1,
        'shortname'       => 'management_console_service',
    ],
];
