<?php
// This file is part of Moodle - http://moodle.org/

defined('MOODLE_INTERNAL') || die();

$functions = [
    'local_adminer_get_users_kpis' => [
        'classname'     => 'local_adminer_api\external\users',
        'methodname'    => 'get_users_kpis',
        'description'   => 'Get global user KPIs (totals, active, suspended, avg progress)',
        'type'          => 'read',
        'capabilities'  => 'moodle/user:viewalldetails',
        'ajax'          => true,
    ],
    'local_adminer_get_dashboard' => [
        'classname'     => 'local_adminer_api\external\dashboard',
        'methodname'    => 'get_dashboard',
        'description'   => 'Get dashboard overview counters',
        'type'          => 'read',
        'capabilities'  => 'moodle/site:config',
        'ajax'          => true,
    ],
    'local_adminer_get_courses' => [
        'classname'     => 'local_adminer_api\external\courses',
        'methodname'    => 'get_courses',
        'description'   => 'Get paginated courses with filtering and stats',
        'type'          => 'read',
        'capabilities'  => 'moodle/course:view',
        'ajax'          => true,
    ],
    'local_adminer_course_action' => [
        'classname'     => 'local_adminer_api\external\courses',
        'methodname'    => 'course_action',
        'description'   => 'Execute individual or bulk actions on courses',
        'type'          => 'write',
        'capabilities'  => 'moodle/course:update',
        'ajax'          => true,
    ],
    'local_adminer_get_categories' => [
        'classname'     => 'local_adminer_api\external\categories',
        'methodname'    => 'get_categories',
        'description'   => 'Get paginated categories with course count and visibility',
        'type'          => 'read',
        'capabilities'  => 'moodle/category:viewhiddencategories',
        'ajax'          => true,
    ],
    'local_adminer_get_categories_flat' => [
        'classname'     => 'local_adminer_api\external\categories',
        'methodname'    => 'get_categories_flat',
        'description'   => 'Get flat list of all categories for selects/dropdowns',
        'type'          => 'read',
        'capabilities'  => 'moodle/category:viewhiddencategories',
        'ajax'          => true,
    ],
    'local_adminer_category_action' => [
        'classname'     => 'local_adminer_api\external\categories',
        'methodname'    => 'category_action',
        'description'   => 'Execute create, update, delete or visibility action on categories',
        'type'          => 'write',
        'capabilities'  => 'moodle/category:manage',
        'ajax'          => true,
    ],
    'local_adminer_get_users' => [
        'classname'     => 'local_adminer_api\external\users',
        'methodname'    => 'get_users',
        'description'   => 'Get paginated users with enrollments, completions, and progress',
        'type'          => 'read',
        'capabilities'  => 'moodle/user:viewalldetails',
        'ajax'          => true,
    ],
    'local_adminer_user_action' => [
        'classname'     => 'local_adminer_api\external\users',
        'methodname'    => 'user_action',
        'description'   => 'Execute suspend, activate or delete actions on users',
        'type'          => 'write',
        'capabilities'  => 'moodle/user:update',
        'ajax'          => true,
    ],
    'local_adminer_get_cohorts_kpis' => [
        'classname'     => 'local_adminer_api\external\cohorts',
        'methodname'    => 'get_cohorts_kpis',
        'description'   => 'Get global cohort KPIs (totals, members, synced courses)',
        'type'          => 'read',
        'capabilities'  => 'moodle/cohort:view',
        'ajax'          => true,
    ],
    'local_adminer_get_cohorts' => [
        'classname'     => 'local_adminer_api\external\cohorts',
        'methodname'    => 'get_cohorts',
        'description'   => 'Get paginated list of cohorts and member counts',
        'type'          => 'read',
        'capabilities'  => 'moodle/cohort:view',
        'ajax'          => true,
    ],
    'local_adminer_cohort_action' => [
        'classname'     => 'local_adminer_api\external\cohorts',
        'methodname'    => 'cohort_action',
        'description'   => 'Execute create, edit or delete actions on cohorts',
        'type'          => 'write',
        'capabilities'  => 'moodle/cohort:manage',
        'ajax'          => true,
    ],
    'local_adminer_get_course_detail' => [
        'classname'     => 'local_adminer_api\external\courses',
        'methodname'    => 'get_course_detail',
        'description'   => 'Get course details including enrolled users and linked cohorts',
        'type'          => 'read',
        'capabilities'  => 'moodle/course:view',
        'ajax'          => true,
    ],
    'local_adminer_course_cohort_action' => [
        'classname'     => 'local_adminer_api\external\courses',
        'methodname'    => 'course_cohort_action',
        'description'   => 'Add or remove cohorts from a course',
        'type'          => 'write',
        'capabilities'  => 'moodle/course:enrolreview',
        'ajax'          => true,
    ],
    'local_adminer_get_user_detail' => [
        'classname'     => 'local_adminer_api\external\users',
        'methodname'    => 'get_user_detail',
        'description'   => 'Get user details including enrolled courses and linked cohorts',
        'type'          => 'read',
        'capabilities'  => 'moodle/user:viewalldetails',
        'ajax'          => true,
    ],
    'local_adminer_user_cohort_action' => [
        'classname'     => 'local_adminer_api\external\users',
        'methodname'    => 'user_cohort_action',
        'description'   => 'Add or remove cohorts from a user',
        'type'          => 'write',
        'capabilities'  => 'moodle/cohort:manage',
        'ajax'          => true,
    ],
    'local_adminer_get_cohort_detail' => [
        'classname'     => 'local_adminer_api\external\cohorts',
        'methodname'    => 'get_cohort_detail',
        'description'   => 'Get cohort details including members and linked courses',
        'type'          => 'read',
        'capabilities'  => 'moodle/cohort:view',
        'ajax'          => true,
    ],
    'local_adminer_get_category_detail' => [
        'classname'     => 'local_adminer_api\external\categories',
        'methodname'    => 'get_category_detail',
        'description'   => 'Get category details including subcategories and courses',
        'type'          => 'read',
        'capabilities'  => 'moodle/category:viewhiddencategories',
        'ajax'          => true,
    ],
    'local_adminer_get_permissions' => [
        'classname'     => 'local_adminer_api\external\permissions',
        'methodname'    => 'get_permissions',
        'description'   => 'Get current user adminer capabilities',
        'type'          => 'read',
        'ajax'          => true,
    ],
    'local_adminer_add_user' => [
        'classname'     => 'local_adminer_api\external\users',
        'methodname'    => 'add_user',
        'description'   => 'Add a new user',
        'type'          => 'write',
        'capabilities'  => 'moodle/user:create',
        'ajax'          => true,
    ],
    'local_adminer_upload_users_csv' => [
        'classname'     => 'local_adminer_api\external\users',
        'methodname'    => 'upload_users_csv',
        'description'   => 'Upload users via CSV',
        'type'          => 'write',
        'capabilities'  => 'moodle/user:create',
        'ajax'          => true,
    ],
    'local_adminer_course_user_action' => [
        'classname'     => 'local_adminer_api\external\courses',
        'methodname'    => 'course_user_action',
        'description'   => 'Enroll or unenroll users in a course',
        'type'          => 'write',
        'capabilities'  => 'enrol/manual:enrol',
        'ajax'          => true,
    ],
    'local_adminer_upload_courses_csv' => [
        'classname'     => 'local_adminer_api\external\courses',
        'methodname'    => 'upload_courses_csv',
        'description'   => 'Upload courses via CSV',
        'type'          => 'write',
        'capabilities'  => 'moodle/course:create',
        'ajax'          => true,
    ],
    'local_adminer_user_course_action' => [
        'classname'     => 'local_adminer_api\external\users',
        'methodname'    => 'user_course_action',
        'description'   => 'Enroll or unenroll a user in multiple courses',
        'type'          => 'write',
        'capabilities'  => 'enrol/manual:enrol',
        'ajax'          => true,
    ],
    'local_adminer_get_course_user_detail' => [
        'classname'     => 'local_adminer_api\external\courses',
        'methodname'    => 'get_course_user_detail',
        'description'   => 'Get user detail inside a course',
        'type'          => 'read',
        'capabilities'  => 'moodle/course:view',
        'ajax'          => true,
    ],
    'local_adminer_get_autologin_url' => [
        'classname'     => 'local_adminer_api\external\autologin',
        'methodname'    => 'get_autologin_url',
        'description'   => 'Get autologin url',
        'type'          => 'read',
        'ajax'          => true,
    ],
];

$services = [
    'Adminer Service' => [
        'functions' => [
            'local_adminer_get_dashboard',
            'local_adminer_get_courses',
            'local_adminer_course_action',
            'local_adminer_get_categories',
            'local_adminer_get_categories_flat',
            'local_adminer_category_action',
            'local_adminer_get_users_kpis',
            'local_adminer_get_users',
            'local_adminer_user_action',
            'local_adminer_add_user',
            'local_adminer_upload_users_csv',
            'local_adminer_get_cohorts_kpis',
            'local_adminer_get_cohorts',
            'local_adminer_cohort_action',
            'local_adminer_get_course_detail',
            'local_adminer_course_cohort_action',
            'local_adminer_course_user_action',
            'local_adminer_get_user_detail',
            'local_adminer_user_cohort_action',
            'local_adminer_user_course_action',
            'local_adminer_get_cohort_detail',
            'local_adminer_get_category_detail',
            'local_adminer_get_permissions',
            'local_adminer_get_course_user_detail',
            'local_adminer_upload_courses_csv',
            'local_adminer_get_autologin_url',
            'core_webservice_get_site_info',
        ],
        'restrictedusers' => 0,
        'enabled'         => 1,
        'shortname'       => 'adminer_service',
    ],
];
